#!/bin/bash
if [ ! -z ${WAYLAND_DISPLAY+x} ]; then copy_cmd="wl-copy"; elif [ ! -z ${DISPLAY+x} ]; then copy_cmd="xclip -selection clipboard"; else copy_cmd=":"; fi
[ "$1" = "-i" ] && { DATA=$(bash -i |& tee /dev/tty); echo "$DATA" | ansifilter | tb; exit 0; }
[ "$1" = "-ic" ] && { DATA=$(bash -i |& tee /dev/tty); echo "$DATA" | tb; exit 0; }
[ -z "$1" ] || { cat "$1" | $0; exit 0; }
ncat ezup.dev 9999 | tee >(head -n1 | tr -d '\n' | $copy_cmd)
