#!/bin/sh

xinitrc() {
	export DISPLAY=:0
	feh --randomize \
		--bg-scale $HOME/Pictures/Wallpapers/Landscape/*.jpg \
		--bg-scale $HOME/Pictures/Wallpapers/Portrait/*.jpg
	exec sowm
}

trap xinitrc USR1

(
    trap '' USR1

    exec X -ardelay 200 \
           -arinterval 20 \
           -dpms \
           -dpi 192 \
           -nolisten tcp \
           :0 vt1
) &

wait
